[build]
builder = "NIXPACKS"
watchPatterns = ["frontend/**"]

[deploy]
startCommand = "pnpm run build && pnpm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
